### ISSUE TITLE
Korean Crowdin lang files update request

### ISSUE THREAD

**Issue by MagPlum** [sakura-ryoko/malilib#27]
Hello, Here is Korean translation for the MaLiLib named 'ko_kr_2_malilib.json' just to distinguish. Please let me know if there is anything that needs to be corrected. I’ll look into other related mods to Korean translation someday.
[ko_kr_2_malilib.json](https://github.com/user-attachments/files/17972923/ko_kr_2_malilib.json)

I'm glad I could give a little help to such a great mod. Thank you.

**Comment by sakura-ryoko** [comment]
Thank you.

I have just added some entries to MaLiLib; can you check to see if those are added?  Same for MiniHUD since your last upload.

There wasn't a lot added; but just figured I would mention it.

**Comment by sakura-ryoko** [comment]
The imported file is shown here, I have manually fixed some of the translation keys because I've separated out the "Generic" and "Debug" config keys, as they appear in the mod.

Please see this file, with the remaining entries added:

https://github.com/sakura-ryoko/malilib/blob/2c7c59b71595910c93b8b7f3c298cd820e102fc1/src/main/resources/assets/malilib/lang/ko_kr.json

**Comment by sakura-ryoko** [comment]
Merged
